#!/usr/bin/env bash
readonly BASH_BINARY="$(which bash)"
readonly TERMV_SCRIPT_NAME="$(basename "$0")"
readonly TERMV_VERSION=2.0

TERMV_CACHE_DIR="${XDG_CACHE_HOME:-$HOME/.cache}/termv"
TERMV_CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/termv"

TERMV_DEPS=(curl fzf)

TERMV_isINSTALLED=${TERMV_isINSTALLED:-true}

has() {
	case "$(command -v "$1" 2>/dev/null)" in alias*|"") return 1 ; esac
}

need(){
	local prog ; local dependencies_not_installed ;
	for prog in $@; do ! has "$prog" && dependencies_not_installed="${dependencies_not_installed}${prog}, " ; done
	[ -n "${dependencies_not_installed}" ] && { echo "err : missing dependencies, please install: ${dependencies_not_installed%??}."; return 1 ;}
	return 0
}

prnt_log() {
	[[ "${TERMV_LOG:-false}" == false ]] && return 0
	echo "$@"
}

if ! has "${TERMV_SCRIPT_NAME:-termv}" ;then
	prnt_log "wrn : ${TERMV_SCRIPT_NAME:-termv} in not intalled in your path file"
	TERMV_isINSTALLED=false
	TERMV_CONFIG_DIR="$PWD/config"
	TERMV_CACHE_DIR="$PWD/cache"
fi

mkdir -p "${TERMV_CACHE_DIR:?}"

if [ -f "${TERMV_CONFIG_DIR}/config" ] ; then
	prnt_log "log : loading config file from \`${TERMV_CONFIG_DIR}/config\`"
	. "${TERMV_CONFIG_DIR}/config"
else
	prnt_log "wrn : you don't have a config file; using the default settings"
fi

need ${TERMV_DEPS[@]} || exit 1
